version: 2

models:
  - name: dim_opportunity
    description: Contains attribution data linked to an opportunity
    columns:
      - name: opportunity_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: dim_user
    description: List of users (active and non-active) who review applications
    columns:
      - name: user_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: onboarding_applications
    description: Contains key data tied to an application
    columns:
      - name: application_id
        description: Primary key
        tests:
          - unique
          - not_null          

  - name: dim_merchant
    description: List of merchants
    columns:
      - name: merchant_account_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: dim_country
    description: List of countries, including risk level
    columns:
      - name: country_key
        description: Primary key
        tests:
          - unique
          - not_null            